### PR TITLE
4th milestone

### PR DESCRIPTION
**Pull request by IvanDerlich**
- Create a filter property in the Redux store.
- Implement the CategoryFilter component.
- Implement filtering functionality
     - Create the handleFilterChange function.
     - Pass the handleFilterChange to CategoryFilter component

### CODE REVIEW

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :balloon: 

Hi @IvanDerlich, congratulations on a great job done :smile: Having met all the minimum requirements for this milestone :+1: I hereby approve the project :fireworks: 

Kindly merge into the development branch and do not forget to submit the project completion form :slightly_smiling_face: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by IvanDerlich** [comment]
Thanks for the review, Daniel!

**Comment by IvanDerlich** [comment]
Thanks for your time, Sir.

**Comment by IvanDerlich** [comment]
Merging

**Pull request merged**
