### PR TITLE
5th milestone

### PR DESCRIPTION
**Pull request by IvanDerlich**
- Style this app with the styles provided by Microverse

### CODE REVIEW

**Comment by IvanDerlich** [comment]
I decided to manage the segmentation of sections display with React Routing.
According to the design provided, the book list and the category section are in different sections: when one is shown, the other is hidden.
In order to show them separated using routes, I saw (perhaps mistakenly) that the only way to do it was removing the handleFilterUpdate function from BookList and moving it to the CategoryFilter component.
The function needs access to the React store, which means that CategoryFIlter needs to be a container now. I've been taught that containers only have access to the store and the rest of the components get data passed down onto them.

**Comment by IvanDerlich** [comment]
I've been taught that containers only have access to the store and the rest of the components get data passed down onto them.

**Review by whiz25 — APPROVED** [review]
## Approve 👏🏿 
Nice work on the design of the app. Your app looks like the provided mockup. 
Please merge and proceed to the next milestone.


### Martin Afani

**Comment by IvanDerlich** [comment]
Thanks Martin for your time.
:=)

**Pull request merged**
